/* tslint:disable */
/* eslint-disable */
/**
 * JBS Backend Service
 * Journalim Protocol Compatible Backend Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: a@azat.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ErrorResponseModel } from '../models';
import { HTTPValidationError } from '../models';
import { Token } from '../models';
/**
 * TokenApi - axios parameter creator
 * @export
 */
export const TokenApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Token
         * @param {string} grantType 
         * @param {string} username 
         * @param {string} password 
         * @param {string} scope 
         * @param {string} clientId 
         * @param {string} clientSecret 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTokenTokenPostForm: async (grantType: string, username: string, password: string, scope: string, clientId: string, clientSecret: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'grantType' is not null or undefined
            if (grantType === null || grantType === undefined) {
                throw new RequiredError('grantType','Required parameter grantType was null or undefined when calling createTokenTokenPostForm.');
            }
            // verify required parameter 'username' is not null or undefined
            if (username === null || username === undefined) {
                throw new RequiredError('username','Required parameter username was null or undefined when calling createTokenTokenPostForm.');
            }
            // verify required parameter 'password' is not null or undefined
            if (password === null || password === undefined) {
                throw new RequiredError('password','Required parameter password was null or undefined when calling createTokenTokenPostForm.');
            }
            // verify required parameter 'scope' is not null or undefined
            if (scope === null || scope === undefined) {
                throw new RequiredError('scope','Required parameter scope was null or undefined when calling createTokenTokenPostForm.');
            }
            // verify required parameter 'clientId' is not null or undefined
            if (clientId === null || clientId === undefined) {
                throw new RequiredError('clientId','Required parameter clientId was null or undefined when calling createTokenTokenPostForm.');
            }
            // verify required parameter 'clientSecret' is not null or undefined
            if (clientSecret === null || clientSecret === undefined) {
                throw new RequiredError('clientSecret','Required parameter clientSecret was null or undefined when calling createTokenTokenPostForm.');
            }
            const localVarPath = `/token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();


            if (grantType !== undefined) { 
                localVarFormParams.set('grant_type', grantType as any);
            }

            if (username !== undefined) { 
                localVarFormParams.set('username', username as any);
            }

            if (password !== undefined) { 
                localVarFormParams.set('password', password as any);
            }

            if (scope !== undefined) { 
                localVarFormParams.set('scope', scope as any);
            }

            if (clientId !== undefined) { 
                localVarFormParams.set('client_id', clientId as any);
            }

            if (clientSecret !== undefined) { 
                localVarFormParams.set('client_secret', clientSecret as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TokenApi - functional programming interface
 * @export
 */
export const TokenApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Token
         * @param {string} grantType 
         * @param {string} username 
         * @param {string} password 
         * @param {string} scope 
         * @param {string} clientId 
         * @param {string} clientSecret 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTokenTokenPostForm(grantType: string, username: string, password: string, scope: string, clientId: string, clientSecret: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Token>>> {
            const localVarAxiosArgs = await TokenApiAxiosParamCreator(configuration).createTokenTokenPostForm(grantType, username, password, scope, clientId, clientSecret, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TokenApi - factory interface
 * @export
 */
export const TokenApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create Token
         * @param {string} grantType 
         * @param {string} username 
         * @param {string} password 
         * @param {string} scope 
         * @param {string} clientId 
         * @param {string} clientSecret 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTokenTokenPostForm(grantType: string, username: string, password: string, scope: string, clientId: string, clientSecret: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Token>> {
            return TokenApiFp(configuration).createTokenTokenPostForm(grantType, username, password, scope, clientId, clientSecret, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TokenApi - object-oriented interface
 * @export
 * @class TokenApi
 * @extends {BaseAPI}
 */
export class TokenApi extends BaseAPI {
    /**
     * 
     * @summary Create Token
     * @param {string} grantType 
     * @param {string} username 
     * @param {string} password 
     * @param {string} scope 
     * @param {string} clientId 
     * @param {string} clientSecret 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApi
     */
    public async createTokenTokenPostForm(grantType: string, username: string, password: string, scope: string, clientId: string, clientSecret: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Token>> {
        return TokenApiFp(this.configuration).createTokenTokenPostForm(grantType, username, password, scope, clientId, clientSecret, options).then((request) => request(this.axios, this.basePath));
    }
}
