/*
 * JBS Backend Service
 * Journalim Protocol Compatible Backend Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: a@azat.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AttachmentCreate;
import io.swagger.client.model.AttachmentRead;
import io.swagger.client.model.AttachmentUpdate;
import io.swagger.client.model.ErrorResponseModel;
import io.swagger.client.model.HTTPValidationError;
import io.swagger.client.model.SuccessResponseModel;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AttachmentApi
 */
@Ignore
public class AttachmentApiTest {

    private final AttachmentApi api = new AttachmentApi();

    /**
     * Create Attachment
     *
     * Create a Attachment.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createAttachmentAttachmentsPostTest() throws Exception {
        AttachmentCreate body = null;
        AttachmentRead response = api.createAttachmentAttachmentsPost(body);

        // TODO: test validations
    }
    /**
     * Delete Attachment
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteAttachmentAttachmentsAttachmentIdDeleteTest() throws Exception {
        Integer attachmentId = null;
        SuccessResponseModel response = api.deleteAttachmentAttachmentsAttachmentIdDelete(attachmentId);

        // TODO: test validations
    }
    /**
     * Read Attachment
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void readAttachmentAttachmentsAttachmentIdGetTest() throws Exception {
        Integer attachmentId = null;
        AttachmentRead response = api.readAttachmentAttachmentsAttachmentIdGet(attachmentId);

        // TODO: test validations
    }
    /**
     * Read Attachments
     *
     * Get all Attachment.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void readAttachmentsAttachmentsGetTest() throws Exception {
        String q = null;
        Integer offset = null;
        Integer limit = null;
        List<AttachmentRead> response = api.readAttachmentsAttachmentsGet(q, offset, limit);

        // TODO: test validations
    }
    /**
     * Update Attachment
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateAttachmentAttachmentsAttachmentIdPatchTest() throws Exception {
        AttachmentUpdate body = null;
        Integer attachmentId = null;
        AttachmentRead response = api.updateAttachmentAttachmentsAttachmentIdPatch(body, attachmentId);

        // TODO: test validations
    }
}
