/*
 * JBS Backend Service
 * Journalim Protocol Compatible Backend Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: a@azat.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ErrorResponseModel;
import io.swagger.client.model.HTTPValidationError;
import io.swagger.client.model.Token;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for TokenApi
 */
@Ignore
public class TokenApiTest {

    private final TokenApi api = new TokenApi();

    /**
     * Create Token
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createTokenTokenPostTest() throws Exception {
        String grantType = null;
        String username = null;
        String password = null;
        String scope = null;
        String clientId = null;
        String clientSecret = null;
        Token response = api.createTokenTokenPost(grantType, username, password, scope, clientId, clientSecret);

        // TODO: test validations
    }
}
