version: '3.9'

services:
  db:
    image: postgres:latest
    #    expose:
    #      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=journalim