/**
 * JBS Backend Service
 * Journalim Protocol Compatible Backend Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: a@azat.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param createdAt 
 * @param updatedAt 
 * @param title 
 * @param description 
 * @param keywords 
 * @param content 
 * @param postId 
 * @param languageId 
 * @param id 
 */
data class PostLanguageRead (

    val createdAt: java.time.LocalDateTime? = null,
    val updatedAt: java.time.LocalDateTime? = null,
    val title: kotlin.String,
    val description: kotlin.String? = null,
    val keywords: kotlin.String? = null,
    val content: kotlin.String? = null,
    val postId: kotlin.Int? = null,
    val languageId: kotlin.Int? = null,
    val id: kotlin.Int
) {
}