/* tslint:disable */
/* eslint-disable */
/**
 * JBS Backend Service
 * Journalim Protocol Compatible Backend Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: a@azat.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GenericFileUploadResponse
 */
export interface GenericFileUploadResponse {
    /**
     * 
     * @type {string}
     * @memberof GenericFileUploadResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GenericFileUploadResponse
     */
    contentType: string;
    /**
     * 
     * @type {string}
     * @memberof GenericFileUploadResponse
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof GenericFileUploadResponse
     */
    accessUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof GenericFileUploadResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof GenericFileUploadResponse
     */
    accessType?: string;
}
