/* tslint:disable */
/* eslint-disable */
/**
 * JBS Backend Service
 * Journalim Protocol Compatible Backend Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: a@azat.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MediaRead
 */
export interface MediaRead {
    /**
     * 
     * @type {Date}
     * @memberof MediaRead
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MediaRead
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof MediaRead
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MediaRead
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof MediaRead
     */
    contentType: string;
    /**
     * 
     * @type {string}
     * @memberof MediaRead
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaRead
     */
    accessUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaRead
     */
    accessType?: string;
    /**
     * 
     * @type {number}
     * @memberof MediaRead
     */
    id: number;
}
