/* tslint:disable */
/* eslint-disable */
/**
 * JBS Backend Service
 * Journalim Protocol Compatible Backend Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: a@azat.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PublicationRead
 */
export interface PublicationRead {
    /**
     * 
     * @type {Date}
     * @memberof PublicationRead
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PublicationRead
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PublicationRead
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationRead
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationRead
     */
    publisher?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationRead
     */
    issn?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationRead
     */
    isbn?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationRead
     */
    editorInChief?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationRead
     */
    editorOthers?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationRead
     */
    contactPerson?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationRead
     */
    contactEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationRead
     */
    contactNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationRead
     */
    contactAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationRead
     */
    subscriptionFee?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationRead
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationRead
     */
    keywords?: string;
    /**
     * This can be a very long html or markdown content
     * @type {string}
     * @memberof PublicationRead
     */
    longDescription?: string;
    /**
     * 
     * @type {number}
     * @memberof PublicationRead
     */
    id: number;
}
