/* tslint:disable */
/* eslint-disable */
/**
 * JBS Backend Service
 * Journalim Protocol Compatible Backend Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: a@azat.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PublicationLanguageUpdate
 */
export interface PublicationLanguageUpdate {
    /**
     * 
     * @type {string}
     * @memberof PublicationLanguageUpdate
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationLanguageUpdate
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationLanguageUpdate
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationLanguageUpdate
     */
    keywords?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationLanguageUpdate
     */
    longDescription?: string;
}
