/*
 * JBS Backend Service
 * Journalim Protocol Compatible Backend Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: a@azat.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JbsBackendService);
  }
}(this, function(expect, JbsBackendService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JbsBackendService.LanguageApi();
  });

  describe('(package)', function() {
    describe('LanguageApi', function() {
      describe('createLanguageLanguagesPost', function() {
        it('should call createLanguageLanguagesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for createLanguageLanguagesPost call and complete the assertions
          /*

          instance.createLanguageLanguagesPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(JbsBackendService.LanguageRead);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteLanguageLanguagesLanguageIdDelete', function() {
        it('should call deleteLanguageLanguagesLanguageIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteLanguageLanguagesLanguageIdDelete call and complete the assertions
          /*

          instance.deleteLanguageLanguagesLanguageIdDelete(languageId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(JbsBackendService.SuccessResponseModel);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('readLanguageLanguagesLanguageIdGet', function() {
        it('should call readLanguageLanguagesLanguageIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for readLanguageLanguagesLanguageIdGet call and complete the assertions
          /*

          instance.readLanguageLanguagesLanguageIdGet(languageId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(JbsBackendService.LanguageRead);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('readLanguagesLanguagesGet', function() {
        it('should call readLanguagesLanguagesGet successfully', function(done) {
          // TODO: uncomment, update parameter values for readLanguagesLanguagesGet call and complete the assertions
          /*
          var opts = {};

          instance.readLanguagesLanguagesGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(JbsBackendService.LanguageRead);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateLanguageLanguagesLanguageIdPatch', function() {
        it('should call updateLanguageLanguagesLanguageIdPatch successfully', function(done) {
          // TODO: uncomment, update parameter values for updateLanguageLanguagesLanguageIdPatch call and complete the assertions
          /*

          instance.updateLanguageLanguagesLanguageIdPatch(body, languageId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(JbsBackendService.LanguageRead);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
