/*
 * JBS Backend Service
 * Journalim Protocol Compatible Backend Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: a@azat.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JbsBackendService);
  }
}(this, function(expect, JbsBackendService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JbsBackendService.PageApi();
  });

  describe('(package)', function() {
    describe('PageApi', function() {
      describe('createPageLanguagePageLanguagesPost', function() {
        it('should call createPageLanguagePageLanguagesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for createPageLanguagePageLanguagesPost call and complete the assertions
          /*

          instance.createPageLanguagePageLanguagesPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(JbsBackendService.PageLanguageRead);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createPagePagesPost', function() {
        it('should call createPagePagesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for createPagePagesPost call and complete the assertions
          /*

          instance.createPagePagesPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(JbsBackendService.PageRead);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deletePageLanguagePageLanguagesPageLanguageIdDelete', function() {
        it('should call deletePageLanguagePageLanguagesPageLanguageIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for deletePageLanguagePageLanguagesPageLanguageIdDelete call and complete the assertions
          /*

          instance.deletePageLanguagePageLanguagesPageLanguageIdDelete(pageLanguageId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(JbsBackendService.SuccessResponseModel);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deletePagePagesPageIdDelete', function() {
        it('should call deletePagePagesPageIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for deletePagePagesPageIdDelete call and complete the assertions
          /*

          instance.deletePagePagesPageIdDelete(pageId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(JbsBackendService.SuccessResponseModel);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('readPageLanguagePageLanguagesPageLanguageIdGet', function() {
        it('should call readPageLanguagePageLanguagesPageLanguageIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for readPageLanguagePageLanguagesPageLanguageIdGet call and complete the assertions
          /*

          instance.readPageLanguagePageLanguagesPageLanguageIdGet(pageLanguageId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(JbsBackendService.PageLanguageRead);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('readPageLanguagesPageLanguagesGet', function() {
        it('should call readPageLanguagesPageLanguagesGet successfully', function(done) {
          // TODO: uncomment, update parameter values for readPageLanguagesPageLanguagesGet call and complete the assertions
          /*
          var opts = {};

          instance.readPageLanguagesPageLanguagesGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(JbsBackendService.PageLanguageRead);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('readPagePagesPageIdGet', function() {
        it('should call readPagePagesPageIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for readPagePagesPageIdGet call and complete the assertions
          /*

          instance.readPagePagesPageIdGet(pageId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(JbsBackendService.PageRead);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('readPagesPagesGet', function() {
        it('should call readPagesPagesGet successfully', function(done) {
          // TODO: uncomment, update parameter values for readPagesPagesGet call and complete the assertions
          /*
          var opts = {};

          instance.readPagesPagesGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(JbsBackendService.PageRead);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updatePageLanguagePageLanguagesPageLanguageIdPatch', function() {
        it('should call updatePageLanguagePageLanguagesPageLanguageIdPatch successfully', function(done) {
          // TODO: uncomment, update parameter values for updatePageLanguagePageLanguagesPageLanguageIdPatch call and complete the assertions
          /*

          instance.updatePageLanguagePageLanguagesPageLanguageIdPatch(body, pageLanguageId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(JbsBackendService.PageLanguageRead);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updatePagePagesPageIdPatch', function() {
        it('should call updatePagePagesPageIdPatch successfully', function(done) {
          // TODO: uncomment, update parameter values for updatePagePagesPageIdPatch call and complete the assertions
          /*

          instance.updatePagePagesPageIdPatch(body, pageId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(JbsBackendService.PageRead);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
