# coding: utf-8

"""
    JBS Backend Service

    Journalim Protocol Compatible Backend Service  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: a@azat.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LanguageRead(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'code': 'str',
        'name_local': 'str',
        'name_global': 'str',
        'id': 'int'
    }

    attribute_map = {
        'created_at': 'created_at',
        'updated_at': 'updated_at',
        'code': 'code',
        'name_local': 'name_local',
        'name_global': 'name_global',
        'id': 'id'
    }

    def __init__(self, created_at=None, updated_at=None, code=None, name_local=None, name_global=None, id=None):  # noqa: E501
        """LanguageRead - a model defined in Swagger"""  # noqa: E501
        self._created_at = None
        self._updated_at = None
        self._code = None
        self._name_local = None
        self._name_global = None
        self._id = None
        self.discriminator = None
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        self.code = code
        self.name_local = name_local
        if name_global is not None:
            self.name_global = name_global
        self.id = id

    @property
    def created_at(self):
        """Gets the created_at of this LanguageRead.  # noqa: E501


        :return: The created_at of this LanguageRead.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this LanguageRead.


        :param created_at: The created_at of this LanguageRead.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this LanguageRead.  # noqa: E501


        :return: The updated_at of this LanguageRead.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this LanguageRead.


        :param updated_at: The updated_at of this LanguageRead.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def code(self):
        """Gets the code of this LanguageRead.  # noqa: E501


        :return: The code of this LanguageRead.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this LanguageRead.


        :param code: The code of this LanguageRead.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def name_local(self):
        """Gets the name_local of this LanguageRead.  # noqa: E501


        :return: The name_local of this LanguageRead.  # noqa: E501
        :rtype: str
        """
        return self._name_local

    @name_local.setter
    def name_local(self, name_local):
        """Sets the name_local of this LanguageRead.


        :param name_local: The name_local of this LanguageRead.  # noqa: E501
        :type: str
        """
        if name_local is None:
            raise ValueError("Invalid value for `name_local`, must not be `None`")  # noqa: E501

        self._name_local = name_local

    @property
    def name_global(self):
        """Gets the name_global of this LanguageRead.  # noqa: E501


        :return: The name_global of this LanguageRead.  # noqa: E501
        :rtype: str
        """
        return self._name_global

    @name_global.setter
    def name_global(self, name_global):
        """Sets the name_global of this LanguageRead.


        :param name_global: The name_global of this LanguageRead.  # noqa: E501
        :type: str
        """

        self._name_global = name_global

    @property
    def id(self):
        """Gets the id of this LanguageRead.  # noqa: E501


        :return: The id of this LanguageRead.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LanguageRead.


        :param id: The id of this LanguageRead.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LanguageRead, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LanguageRead):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
