# coding: utf-8

"""
    JBS Backend Service

    Journalim Protocol Compatible Backend Service  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: a@azat.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SiteRead(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'title': 'str',
        'description': 'str',
        'logo': 'str',
        'site_url': 'str',
        'id': 'int'
    }

    attribute_map = {
        'created_at': 'created_at',
        'updated_at': 'updated_at',
        'title': 'title',
        'description': 'description',
        'logo': 'logo',
        'site_url': 'site_url',
        'id': 'id'
    }

    def __init__(self, created_at=None, updated_at=None, title=None, description=None, logo=None, site_url=None, id=None):  # noqa: E501
        """SiteRead - a model defined in Swagger"""  # noqa: E501
        self._created_at = None
        self._updated_at = None
        self._title = None
        self._description = None
        self._logo = None
        self._site_url = None
        self._id = None
        self.discriminator = None
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        self.title = title
        if description is not None:
            self.description = description
        if logo is not None:
            self.logo = logo
        if site_url is not None:
            self.site_url = site_url
        self.id = id

    @property
    def created_at(self):
        """Gets the created_at of this SiteRead.  # noqa: E501


        :return: The created_at of this SiteRead.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this SiteRead.


        :param created_at: The created_at of this SiteRead.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this SiteRead.  # noqa: E501


        :return: The updated_at of this SiteRead.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this SiteRead.


        :param updated_at: The updated_at of this SiteRead.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def title(self):
        """Gets the title of this SiteRead.  # noqa: E501


        :return: The title of this SiteRead.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this SiteRead.


        :param title: The title of this SiteRead.  # noqa: E501
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def description(self):
        """Gets the description of this SiteRead.  # noqa: E501


        :return: The description of this SiteRead.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this SiteRead.


        :param description: The description of this SiteRead.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def logo(self):
        """Gets the logo of this SiteRead.  # noqa: E501


        :return: The logo of this SiteRead.  # noqa: E501
        :rtype: str
        """
        return self._logo

    @logo.setter
    def logo(self, logo):
        """Sets the logo of this SiteRead.


        :param logo: The logo of this SiteRead.  # noqa: E501
        :type: str
        """

        self._logo = logo

    @property
    def site_url(self):
        """Gets the site_url of this SiteRead.  # noqa: E501


        :return: The site_url of this SiteRead.  # noqa: E501
        :rtype: str
        """
        return self._site_url

    @site_url.setter
    def site_url(self, site_url):
        """Sets the site_url of this SiteRead.


        :param site_url: The site_url of this SiteRead.  # noqa: E501
        :type: str
        """

        self._site_url = site_url

    @property
    def id(self):
        """Gets the id of this SiteRead.  # noqa: E501


        :return: The id of this SiteRead.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SiteRead.


        :param id: The id of this SiteRead.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SiteRead, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SiteRead):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
