//
// GenericFileUploadResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GenericFileUploadResponse: Codable {

    public var name: String
    public var contentType: String
    public var path: AnyOfGenericFileUploadResponsePath?
    public var accessUrl: String?
    public var _description: String?
    public var accessType: String?

    public init(name: String, contentType: String, path: AnyOfGenericFileUploadResponsePath? = nil, accessUrl: String? = nil, _description: String? = nil, accessType: String? = nil) {
        self.name = name
        self.contentType = contentType
        self.path = path
        self.accessUrl = accessUrl
        self._description = _description
        self.accessType = accessType
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case contentType = "content_type"
        case path
        case accessUrl = "access_url"
        case _description = "description"
        case accessType = "access_type"
    }

}
