//
// LanguageUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LanguageUpdate: Codable {

    public var code: String?
    public var nameLocal: String?
    public var nameGlobal: String?

    public init(code: String? = nil, nameLocal: String? = nil, nameGlobal: String? = nil) {
        self.code = code
        self.nameLocal = nameLocal
        self.nameGlobal = nameGlobal
    }

    public enum CodingKeys: String, CodingKey { 
        case code
        case nameLocal = "name_local"
        case nameGlobal = "name_global"
    }

}
