//
// PageUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PageUpdate: Codable {

    public var title: String?
    public var _description: String?
    public var keywords: String?
    public var author: String?
    public var featuredImage: String?
    public var content: String?

    public init(title: String? = nil, _description: String? = nil, keywords: String? = nil, author: String? = nil, featuredImage: String? = nil, content: String? = nil) {
        self.title = title
        self._description = _description
        self.keywords = keywords
        self.author = author
        self.featuredImage = featuredImage
        self.content = content
    }

    public enum CodingKeys: String, CodingKey { 
        case title
        case _description = "description"
        case keywords
        case author
        case featuredImage = "featured_image"
        case content
    }

}
