//
// PublicationRead.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PublicationRead: Codable {

    public var createdAt: Date?
    public var updatedAt: Date?
    public var title: String
    public var _description: String?
    public var publisher: String?
    public var issn: String?
    public var isbn: String?
    public var editorInChief: String?
    public var editorOthers: String?
    public var contactPerson: String?
    public var contactEmail: String?
    public var contactNumber: String?
    public var contactAddress: String?
    public var subscriptionFee: String?
    public var image: String?
    public var keywords: String?
    /** This can be a very long html or markdown content */
    public var longDescription: String?
    public var _id: Int

    public init(createdAt: Date? = nil, updatedAt: Date? = nil, title: String, _description: String? = nil, publisher: String? = nil, issn: String? = nil, isbn: String? = nil, editorInChief: String? = nil, editorOthers: String? = nil, contactPerson: String? = nil, contactEmail: String? = nil, contactNumber: String? = nil, contactAddress: String? = nil, subscriptionFee: String? = nil, image: String? = nil, keywords: String? = nil, longDescription: String? = nil, _id: Int) {
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.title = title
        self._description = _description
        self.publisher = publisher
        self.issn = issn
        self.isbn = isbn
        self.editorInChief = editorInChief
        self.editorOthers = editorOthers
        self.contactPerson = contactPerson
        self.contactEmail = contactEmail
        self.contactNumber = contactNumber
        self.contactAddress = contactAddress
        self.subscriptionFee = subscriptionFee
        self.image = image
        self.keywords = keywords
        self.longDescription = longDescription
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case title
        case _description = "description"
        case publisher
        case issn
        case isbn
        case editorInChief = "editor_in_chief"
        case editorOthers = "editor_others"
        case contactPerson = "contact_person"
        case contactEmail = "contact_email"
        case contactNumber = "contact_number"
        case contactAddress = "contact_address"
        case subscriptionFee = "subscription_fee"
        case image
        case keywords
        case longDescription = "long_description"
        case _id = "id"
    }

}
