//
// SiteLanguageRead.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteLanguageRead: Codable {

    public var createdAt: Date?
    public var updatedAt: Date?
    public var title: String?
    public var _description: String?
    public var alternativeLogo: String?
    public var siteId: Int?
    public var languageId: Int?
    public var _id: Int

    public init(createdAt: Date? = nil, updatedAt: Date? = nil, title: String? = nil, _description: String? = nil, alternativeLogo: String? = nil, siteId: Int? = nil, languageId: Int? = nil, _id: Int) {
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.title = title
        self._description = _description
        self.alternativeLogo = alternativeLogo
        self.siteId = siteId
        self.languageId = languageId
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case title
        case _description = "description"
        case alternativeLogo = "alternative_logo"
        case siteId = "site_id"
        case languageId = "language_id"
        case _id = "id"
    }

}
