//
// UserCreate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserCreate: Codable {

    public var username: String
    public var email: String
    public var fullname: String?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var password: String

    public init(username: String, email: String, fullname: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, password: String) {
        self.username = username
        self.email = email
        self.fullname = fullname
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.password = password
    }

    public enum CodingKeys: String, CodingKey { 
        case username
        case email
        case fullname
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case password
    }

}
