# coding: utf-8

"""
    JBS Backend Service

    Journalim Protocol Compatible Backend Service  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: a@azat.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_read import UserRead  # noqa: E501
from swagger_client.rest import ApiException


class TestUserRead(unittest.TestCase):
    """UserRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserRead(self):
        """Test UserRead"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_read.UserRead()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
