# coding: utf-8

"""
    JBS Backend Service

    Journalim Protocol Compatible Backend Service  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: a@azat.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.publication_update import PublicationUpdate  # noqa: E501
from swagger_client.rest import ApiException


class TestPublicationUpdate(unittest.TestCase):
    """PublicationUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPublicationUpdate(self):
        """Test PublicationUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.publication_update.PublicationUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
