# coding: utf-8

"""
    JBS Backend Service

    Journalim Protocol Compatible Backend Service  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: a@azat.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.page_api import PageApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPageApi(unittest.TestCase):
    """PageApi unit test stubs"""

    def setUp(self):
        self.api = PageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_page_language_page_languages_post(self):
        """Test case for create_page_language_page_languages_post

        Create Page Language  # noqa: E501
        """
        pass

    def test_create_page_pages_post(self):
        """Test case for create_page_pages_post

        Create Page  # noqa: E501
        """
        pass

    def test_delete_page_language_page_languages_page_language_id_delete(self):
        """Test case for delete_page_language_page_languages_page_language_id_delete

        Delete Page Language  # noqa: E501
        """
        pass

    def test_delete_page_pages_page_id_delete(self):
        """Test case for delete_page_pages_page_id_delete

        Delete Page  # noqa: E501
        """
        pass

    def test_read_page_language_page_languages_page_language_id_get(self):
        """Test case for read_page_language_page_languages_page_language_id_get

        Read Page Language  # noqa: E501
        """
        pass

    def test_read_page_languages_page_languages_get(self):
        """Test case for read_page_languages_page_languages_get

        Read Page Languages  # noqa: E501
        """
        pass

    def test_read_page_pages_page_id_get(self):
        """Test case for read_page_pages_page_id_get

        Read Page  # noqa: E501
        """
        pass

    def test_read_pages_pages_get(self):
        """Test case for read_pages_pages_get

        Read Pages  # noqa: E501
        """
        pass

    def test_update_page_language_page_languages_page_language_id_patch(self):
        """Test case for update_page_language_page_languages_page_language_id_patch

        Update Page Language  # noqa: E501
        """
        pass

    def test_update_page_pages_page_id_patch(self):
        """Test case for update_page_pages_page_id_patch

        Update Page  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
