# coding: utf-8

"""
    JBS Backend Service

    Journalim Protocol Compatible Backend Service  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: a@azat.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.body_create_upload_upload_post import BodyCreateUploadUploadPost  # noqa: E501
from swagger_client.rest import ApiException


class TestBodyCreateUploadUploadPost(unittest.TestCase):
    """BodyCreateUploadUploadPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyCreateUploadUploadPost(self):
        """Test BodyCreateUploadUploadPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body_create_upload_upload_post.BodyCreateUploadUploadPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
