/*
 * JBS Backend Service
 * Journalim Protocol Compatible Backend Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: a@azat.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MediaRead model module.
 * @module model/MediaRead
 * @version 0.0.1
 */
export class MediaRead {
  /**
   * Constructs a new <code>MediaRead</code>.
   * @alias module:model/MediaRead
   * @class
   * @param name {String} 
   * @param path {String} 
   * @param contentType {String} 
   * @param id {Number} 
   */
  constructor(name, path, contentType, id) {
    this.name = name;
    this.path = path;
    this.contentType = contentType;
    this.id = id;
  }

  /**
   * Constructs a <code>MediaRead</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MediaRead} obj Optional instance to populate.
   * @return {module:model/MediaRead} The populated <code>MediaRead</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MediaRead();
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'Date');
      if (data.hasOwnProperty('updated_at'))
        obj.updatedAt = ApiClient.convertToType(data['updated_at'], 'Date');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('path'))
        obj.path = ApiClient.convertToType(data['path'], 'String');
      if (data.hasOwnProperty('content_type'))
        obj.contentType = ApiClient.convertToType(data['content_type'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('access_url'))
        obj.accessUrl = ApiClient.convertToType(data['access_url'], 'String');
      if (data.hasOwnProperty('access_type'))
        obj.accessType = ApiClient.convertToType(data['access_type'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
MediaRead.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
MediaRead.prototype.updatedAt = undefined;

/**
 * @member {String} name
 */
MediaRead.prototype.name = undefined;

/**
 * @member {String} path
 */
MediaRead.prototype.path = undefined;

/**
 * @member {String} contentType
 */
MediaRead.prototype.contentType = undefined;

/**
 * @member {String} description
 */
MediaRead.prototype.description = undefined;

/**
 * @member {String} accessUrl
 */
MediaRead.prototype.accessUrl = undefined;

/**
 * @member {String} accessType
 */
MediaRead.prototype.accessType = undefined;

/**
 * @member {Number} id
 */
MediaRead.prototype.id = undefined;

