/*
 * JBS Backend Service
 * Journalim Protocol Compatible Backend Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: a@azat.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MediaUpdate model module.
 * @module model/MediaUpdate
 * @version 0.0.1
 */
export class MediaUpdate {
  /**
   * Constructs a new <code>MediaUpdate</code>.
   * @alias module:model/MediaUpdate
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MediaUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MediaUpdate} obj Optional instance to populate.
   * @return {module:model/MediaUpdate} The populated <code>MediaUpdate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MediaUpdate();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
MediaUpdate.prototype.name = undefined;

/**
 * @member {String} description
 */
MediaUpdate.prototype.description = undefined;

