/*
 * JBS Backend Service
 * Journalim Protocol Compatible Backend Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: a@azat.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SuccessResponseModel model module.
 * @module model/SuccessResponseModel
 * @version 0.0.1
 */
export class SuccessResponseModel {
  /**
   * Constructs a new <code>SuccessResponseModel</code>.
   * @alias module:model/SuccessResponseModel
   * @class
   * @param message {String} 
   */
  constructor(message) {
    this.message = message;
  }

  /**
   * Constructs a <code>SuccessResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SuccessResponseModel} obj Optional instance to populate.
   * @return {module:model/SuccessResponseModel} The populated <code>SuccessResponseModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SuccessResponseModel();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} message
 */
SuccessResponseModel.prototype.message = undefined;

